### ISSUE TITLE
DMA Transfer Direction

### ISSUE THREAD

**Issue by BlaiseSaunders** [ellectroid/STM32F746-Minimal-UART-DMA-Driver-Demo#1]
Hi there,

Did you ever get this working?
Having a look at `usart_dma_sendArray` I can see the following line

```DMA2_Stream7->CR |= DMA_SxCR_DIR_0; //set direction memory to peripheral```

However RM0385 Rev 8 datasheet says 00 is peripheral to memory, and 01 is memory to peripheral. I can't seem to get your example working but I'm assuming this particular line is a misunderstanding on my part?

Thanks and Kind Regards,
Blaise

**Comment by ellectroid** [comment]
This line of code sets bit 0 of CR to 1, giving the final value of the field 0b01, which is memory to peripheral. DIR_0 is not the value 0 (otherwise I just xor with 0, which is doing nothing). DIR_0 means bit 0 set. The problem should be somewhere else.
